version: '3'
services:
  proxy:
    image: traefik:1.7.9-alpine
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sds
    labels:
      - "traefik.docker.network=sds"
    restart: always
  # db:
  #   image: mongo:4.0.6-xenial
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASS}
  #   volumes:
  #     - db-data:/data/db
  #   restart: always
  # dbui:
  #   image: mongo-express:0.49.0
  #   depends_on:
  #     - proxy
  #     - db
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASS}
  #     ME_CONFIG_MONGODB_SERVER: db
  #   labels:
  #     - "traefik.frontend.rule=Host:dbadmin.${HOST_NAME}"
  #     - "traefik.port=8081"
  #   restart: always
  room:
    image: samchatfield/sds-room-service
    depends_on:
      - proxy
      # - db
    volumes:
      - /usr/src/app/node_modules/
      - ./room-service/.env:/usr/src/app/.env
    networks:
      - sds
    labels:
      - "traefik.docker.network=sds"
      - "traefik.frontend.rule=PathPrefixStrip:/api/room"
      - "traefik.port=3000"
    restart: always
  user:
    image: samchatfield/sds-user-service
    depends_on:
      - proxy
      # - db
    volumes:
      - /usr/src/app/node_modules/
      - user-uploads:/usr/src/app/public/files
      - ./user-service/.env:/usr/src/app/.env
    networks:
      - sds
    labels:
      - "traefik.docker.network=sds"
      - "traefik.frontend.rule=PathPrefixStrip:/api/user"
      - "traefik.port=3000"
    restart: always
volumes:
  # db-data:
  user-uploads:
networks:
  sds:
    external: true
